export interface Product {
  id: string
  name: string
  category: string
  description: string
  fragranceFamily: string
  topNotes: string
  heartNotes: string
  baseNotes: string
  longevity: string
  bestFor: string
  occasion: string
  season: string
  size: string
  price: string
  image: string
  stock: boolean
}

export const allProducts: Product[] = [
  // PERFUMES
  {
    id: 'perfume-1',
    name: 'Midnight Resonance',
    category: 'Perfumes',
    description: 'A refined evening fragrance with oud, amber and sandalwood, created for elegant occasions.',
    fragranceFamily: 'Woody Oriental',
    topNotes: 'Bergamot, Pink Pepper',
    heartNotes: 'Oud, Amber',
    baseNotes: 'Sandalwood, Musk, Leather',
    longevity: '8-10 hours',
    bestFor: 'Evening wear, special occasions',
    occasion: 'Formal events, evening outings',
    season: 'Autumn, Winter',
    size: '50ml',
    price: '₦35,000',
    image: '/perfume-midnight-resonance.png',
    stock: true,
  },
  {
    id: 'perfume-2',
    name: 'Golden Aura',
    category: 'Perfumes',
    description: 'Warm vanilla, jasmine and soft musk with exceptional longevity for all-day wear.',
    fragranceFamily: 'Amber Floral',
    topNotes: 'Lemon, Neroli',
    heartNotes: 'Jasmine, Orange Blossom',
    baseNotes: 'Vanilla, Musk, Amber',
    longevity: '10-12 hours',
    bestFor: 'All day wear, work, casual',
    occasion: 'Daily wear, professional settings',
    season: 'Spring, Summer, Autumn',
    size: '100ml',
    price: '₦48,000',
    image: '/perfume-golden-aura.png',
    stock: true,
  },
  {
    id: 'perfume-3',
    name: 'Executive Signature',
    category: 'Perfumes',
    description: 'A sophisticated fragrance designed for professionals who appreciate quiet confidence.',
    fragranceFamily: 'Woody Aromatic',
    topNotes: 'Grapefruit, Ginger',
    heartNotes: 'Cedarwood, Vetiver',
    baseNotes: 'Sandalwood, Tobacco Leaf, Musk',
    longevity: '10-12 hours',
    bestFor: 'Professional, business settings',
    occasion: 'Work, meetings, corporate events',
    season: 'Year-round',
    size: '100ml',
    price: '₦65,000',
    image: '/perfume-executive-signature.png',
    stock: true,
  },
  {
    id: 'perfume-4',
    name: 'Velvet Bloom',
    category: 'Perfumes',
    description: 'Rose, peony and white musk blended into a luxurious feminine scent.',
    fragranceFamily: 'Floral Musk',
    topNotes: 'Red Currant, Freesia',
    heartNotes: 'Rose, Peony, Geranium',
    baseNotes: 'White Musk, Iris, Sandalwood',
    longevity: '8-10 hours',
    bestFor: 'Everyday wear, romantic occasions',
    occasion: 'Dates, casual outings, evening',
    season: 'Spring, Summer',
    size: '100ml',
    price: '₦82,000',
    image: '/perfume-velvet-bloom.png',
    stock: true,
  },
  {
    id: 'perfume-5',
    name: 'Imperial Oud Reserve',
    category: 'Perfumes',
    description: 'Premium oud with saffron, leather and amber for the connoisseur.',
    fragranceFamily: 'Luxury Oud',
    topNotes: 'Saffron, Pink Peppercorn',
    heartNotes: 'Oud, Leather',
    baseNotes: 'Amber, Agarwood, Musk',
    longevity: '12+ hours',
    bestFor: 'Special occasions, collectors',
    occasion: 'Luxurious evenings, celebrations',
    season: 'Autumn, Winter',
    size: '100ml',
    price: '₦150,000',
    image: '/perfume-imperial-oud.png',
    stock: true,
  },
  {
    id: 'perfume-6',
    name: 'Noir Prestige Elixir',
    category: 'Perfumes',
    description: 'An exclusive fragrance with rich spices, patchouli and precious woods.',
    fragranceFamily: 'Oriental',
    topNotes: 'Cardamom, Clove',
    heartNotes: 'Patchouli, Cinnamon',
    baseNotes: 'Oud, Precious Wood, Amber',
    longevity: '12+ hours',
    bestFor: 'Evening wear, special occasions',
    occasion: 'Formal events, evening gatherings',
    season: 'Autumn, Winter',
    size: '100ml',
    price: '₦250,000',
    image: '/perfume-noir-prestige.png',
    stock: true,
  },
  {
    id: 'perfume-7',
    name: 'VIZZANG Signature Collection',
    category: 'Perfumes',
    description: 'Luxury limited edition fragrance in handcrafted premium packaging.',
    fragranceFamily: 'Luxury Blend',
    topNotes: 'Bergamot, Saffron',
    heartNotes: 'Rose, Oud, Jasmine',
    baseNotes: 'Sandalwood, Amber, Musk',
    longevity: '14+ hours',
    bestFor: 'Collectors, special gifting',
    occasion: 'Exclusive events, milestones',
    season: 'Year-round',
    size: '100ml',
    price: '₦500,000',
    image: '/perfume-vizzang-signature.png',
    stock: false,
  },

  // PERFUME OILS
  {
    id: 'oil-1',
    name: 'White Musk Essence',
    category: 'Perfume Oils',
    description: 'Pure white musk oil for intimate, close-wear fragrance.',
    fragranceFamily: 'White Musk',
    topNotes: 'Bergamot',
    heartNotes: 'White Musk',
    baseNotes: 'Sandalwood, Vanilla',
    longevity: '8 hours',
    bestFor: 'Everyday, intimate wear',
    occasion: 'Daily application',
    season: 'Year-round',
    size: '30ml',
    price: '₦20,000',
    image: '/oil-white-musk.png',
    stock: true,
  },
  {
    id: 'oil-2',
    name: 'Royal Vanilla Oil',
    category: 'Perfume Oils',
    description: 'Luxurious vanilla oil with warm spices and amber.',
    fragranceFamily: 'Vanilla Gourmand',
    topNotes: 'Cinnamon',
    heartNotes: 'Vanilla, Tonka',
    baseNotes: 'Amber, Musk',
    longevity: '6-8 hours',
    bestFor: 'Everyday wear, comfortable scent',
    occasion: 'Daily application',
    season: 'Year-round',
    size: '30ml',
    price: '₦25,000',
    image: '/oil-royal-vanilla.png',
    stock: true,
  },
  {
    id: 'oil-3',
    name: 'Golden Amber Oil',
    category: 'Perfume Oils',
    description: 'Warm amber and precious wood concentrate for intense fragrance.',
    fragranceFamily: 'Amber',
    topNotes: 'Orange',
    heartNotes: 'Amber, Resins',
    baseNotes: 'Sandalwood, Vetiver',
    longevity: '8-10 hours',
    bestFor: 'Evening wear, special occasions',
    occasion: 'Formal events',
    season: 'Autumn, Winter',
    size: '25ml',
    price: '₦35,000',
    image: '/oil-golden-amber.png',
    stock: true,
  },
  {
    id: 'oil-4',
    name: 'Soft Oud Concentrate',
    category: 'Perfume Oils',
    description: 'Premium oud oil with floral undertones for sophisticated wear.',
    fragranceFamily: 'Oud',
    topNotes: 'Rose',
    heartNotes: 'Oud',
    baseNotes: 'Musk, Amber',
    longevity: '10+ hours',
    bestFor: 'Special occasions, collectors',
    occasion: 'Evening, formal events',
    season: 'Autumn, Winter',
    size: '20ml',
    price: '₦60,000',
    image: '/oil-soft-oud.png',
    stock: true,
  },
  {
    id: 'oil-5',
    name: 'Velvet Rose Oil',
    category: 'Perfume Oils',
    description: 'Rich rose oil blended with musk for romantic elegance.',
    fragranceFamily: 'Rose',
    topNotes: 'Lemon',
    heartNotes: 'Rose, Peony',
    baseNotes: 'Musk, Sandalwood',
    longevity: '6-8 hours',
    bestFor: 'Romantic occasions, daily wear',
    occasion: 'Dates, casual outings',
    season: 'Spring, Summer',
    size: '30ml',
    price: '₦28,000',
    image: '/oil-velvet-rose.png',
    stock: true,
  },
  {
    id: 'oil-6',
    name: 'Midnight Sandalwood Oil',
    category: 'Perfume Oils',
    description: 'Deep sandalwood oil with spice for evening elegance.',
    fragranceFamily: 'Sandalwood',
    topNotes: 'Cardamom',
    heartNotes: 'Sandalwood',
    baseNotes: 'Vetiver, Musk',
    longevity: '8-10 hours',
    bestFor: 'Evening wear, formal settings',
    occasion: 'Evenings, special events',
    season: 'Autumn, Winter',
    size: '25ml',
    price: '₦40,000',
    image: '/oil-midnight-sandalwood.png',
    stock: true,
  },
  {
    id: 'oil-7',
    name: 'Luxury Signature Oil Blend',
    category: 'Perfume Oils',
    description: 'Exclusive oil blend with premium oud, rose and sandalwood.',
    fragranceFamily: 'Luxury Blend',
    topNotes: 'Saffron',
    heartNotes: 'Rose, Oud',
    baseNotes: 'Sandalwood, Amber',
    longevity: '10+ hours',
    bestFor: 'Special occasions, collectors',
    occasion: 'Exclusive events',
    season: 'Year-round',
    size: '20ml',
    price: '₦120,000',
    image: '/oil-luxury-signature.png',
    stock: true,
  },

  // BODY MISTS
  {
    id: 'mist-1',
    name: 'Fresh Linen Mist',
    category: 'Body Mists',
    description: 'Light and crisp fragrance evoking fresh linen and clean air.',
    fragranceFamily: 'Floral Musk',
    topNotes: 'Lemon, Bergamot',
    heartNotes: 'White Florals',
    baseNotes: 'Musk, Amber',
    longevity: '3-4 hours',
    bestFor: 'Daily layering, refresh spray',
    occasion: 'Daytime wear',
    season: 'Spring, Summer',
    size: '150ml',
    price: '₦22,000',
    image: '/mist-fresh-linen.png',
    stock: true,
  },
  {
    id: 'mist-2',
    name: 'Morning Bloom Mist',
    category: 'Body Mists',
    description: 'Delicate floral spray with fruity top notes for morning freshness.',
    fragranceFamily: 'Fruity Floral',
    topNotes: 'Apple, Peach',
    heartNotes: 'Peony, Rose',
    baseNotes: 'Musk, Vanilla',
    longevity: '3-4 hours',
    bestFor: 'Morning refreshment, layering',
    occasion: 'Morning routines',
    season: 'Spring, Summer',
    size: '150ml',
    price: '₦20,000',
    image: '/body-mist.png',
    stock: true,
  },
  {
    id: 'mist-3',
    name: 'Vanilla Cloud Mist',
    category: 'Body Mists',
    description: 'Soft vanilla and caramel mist for comfort and warmth.',
    fragranceFamily: 'Vanilla Gourmand',
    topNotes: 'Caramel',
    heartNotes: 'Vanilla, Tonka',
    baseNotes: 'Musk, Amber',
    longevity: '3-4 hours',
    bestFor: 'Comfort wear, layering',
    occasion: 'Casual outings',
    season: 'Year-round',
    size: '150ml',
    price: '₦24,000',
    image: '/body-mist.png',
    stock: true,
  },
  {
    id: 'mist-4',
    name: 'Tropical Escape Mist',
    category: 'Body Mists',
    description: 'Exotic tropical fruits and florals for vacation vibes.',
    fragranceFamily: 'Fruity Floral',
    topNotes: 'Mango, Coconut',
    heartNotes: 'Hibiscus, Jasmine',
    baseNotes: 'Musk, Vanilla',
    longevity: '3-4 hours',
    bestFor: 'Summer wear, casual outings',
    occasion: 'Holiday, beach trips',
    season: 'Summer',
    size: '150ml',
    price: '₦20,000',
    image: '/mist-tropical-escape.png',
    stock: true,
  },
  {
    id: 'mist-5',
    name: 'Ocean Breeze Mist',
    category: 'Body Mists',
    description: 'Fresh aquatic fragrance with sea salt and citrus.',
    fragranceFamily: 'Aquatic Citrus',
    topNotes: 'Sea Salt, Lemon',
    heartNotes: 'Aquatic Notes',
    baseNotes: 'Musk, Driftwood',
    longevity: '3-4 hours',
    bestFor: 'Fresh daily wear',
    occasion: 'Daytime, athletic wear',
    season: 'Spring, Summer',
    size: '150ml',
    price: '₦21,000',
    image: '/mist-ocean-breeze.png',
    stock: true,
  },
  {
    id: 'mist-6',
    name: 'Golden Citrus Mist',
    category: 'Body Mists',
    description: 'Energizing citrus blend with warm amber for uplifting fragrance.',
    fragranceFamily: 'Citrus Amber',
    topNotes: 'Grapefruit, Orange',
    heartNotes: 'Neroli',
    baseNotes: 'Amber, Musk',
    longevity: '3-4 hours',
    bestFor: 'Energy boost, daytime wear',
    occasion: 'Morning, work',
    season: 'Spring, Summer',
    size: '150ml',
    price: '₦22,000',
    image: '/mist-golden-citrus.png',
    stock: true,
  },
  {
    id: 'mist-7',
    name: 'Silk Blossom Mist',
    category: 'Body Mists',
    description: 'Luxurious floral with silk-like finish for elegant freshness.',
    fragranceFamily: 'Floral',
    topNotes: 'Rose, Freesia',
    heartNotes: 'Gardenia, Tuberose',
    baseNotes: 'Musk, Sandalwood',
    longevity: '3-4 hours',
    bestFor: 'Evening light wear, layering',
    occasion: 'Evening outings',
    season: 'Year-round',
    size: '150ml',
    price: '₦26,000',
    image: '/mist-silk-blossom.png',
    stock: true,
  },

  // SCENTED CANDLES
  {
    id: 'candle-1',
    name: 'Vanilla Comfort',
    category: 'Scented Candles',
    description: 'Hand-poured soy candle with warm vanilla and caramel notes.',
    fragranceFamily: 'Vanilla Gourmand',
    topNotes: 'Caramel',
    heartNotes: 'Vanilla, Tonka',
    baseNotes: 'Musk, Amber',
    longevity: '40-45 hours burn time',
    bestFor: 'Home ambiance, relaxation',
    occasion: 'Everyday home fragrance',
    season: 'Year-round',
    size: '200g',
    price: '₦32,000',
    image: '/candle-vanilla-comfort.png',
    stock: true,
  },
  {
    id: 'candle-2',
    name: 'Midnight Oud',
    category: 'Scented Candles',
    description: 'Premium oud candle for luxurious evening ambiance.',
    fragranceFamily: 'Oud',
    topNotes: 'Saffron',
    heartNotes: 'Oud',
    baseNotes: 'Amber, Musk',
    longevity: '45-50 hours burn time',
    bestFor: 'Evening ambiance, special occasions',
    occasion: 'Formal events, intimate gatherings',
    season: 'Autumn, Winter',
    size: '200g',
    price: '₦50,000',
    image: '/candle-midnight-oud.png',
    stock: true,
  },
  {
    id: 'candle-3',
    name: 'Fresh Cotton',
    category: 'Scented Candles',
    description: 'Clean linen fragrance with floral undertones for fresh spaces.',
    fragranceFamily: 'Floral Musk',
    topNotes: 'Bergamot',
    heartNotes: 'White Florals',
    baseNotes: 'Musk',
    longevity: '35-40 hours burn time',
    bestFor: 'Daily home fragrance, bedrooms',
    occasion: 'Everyday ambient scenting',
    season: 'Spring, Summer',
    size: '200g',
    price: '₦28,000',
    image: '/candle-fresh-cotton.png',
    stock: true,
  },
  {
    id: 'candle-4',
    name: 'Arabian Nights',
    category: 'Scented Candles',
    description: 'Exotic blend of spices, incense and precious woods.',
    fragranceFamily: 'Oriental Spice',
    topNotes: 'Cardamom, Clove',
    heartNotes: 'Cinnamon, Frankincense',
    baseNotes: 'Sandalwood, Amber',
    longevity: '45-50 hours burn time',
    bestFor: 'Evening ambiance, meditation spaces',
    occasion: 'Relaxation, special evenings',
    season: 'Autumn, Winter',
    size: '200g',
    price: '₦48,000',
    image: '/candle-arabian-nights.png',
    stock: true,
  },
  {
    id: 'candle-5',
    name: 'Golden Sandalwood',
    category: 'Scented Candles',
    description: 'Warm sandalwood with citrus for balanced home fragrance.',
    fragranceFamily: 'Sandalwood Citrus',
    topNotes: 'Orange',
    heartNotes: 'Sandalwood',
    baseNotes: 'Vetiver, Musk',
    longevity: '40-45 hours burn time',
    bestFor: 'All-day home ambiance',
    occasion: 'Year-round home scenting',
    season: 'Year-round',
    size: '200g',
    price: '₦42,000',
    image: '/candle-golden-sandalwood.png',
    stock: true,
  },
  {
    id: 'candle-6',
    name: 'Calm Lavender',
    category: 'Scented Candles',
    description: 'Soothing lavender with chamomile for peaceful spaces.',
    fragranceFamily: 'Herbal Floral',
    topNotes: 'Lavender',
    heartNotes: 'Chamomile',
    baseNotes: 'Musk, Vanilla',
    longevity: '38-42 hours burn time',
    bestFor: 'Relaxation, sleep spaces',
    occasion: 'Evening unwinding, meditation',
    season: 'Year-round',
    size: '200g',
    price: '₦30,000',
    image: '/candle-calm-lavender.png',
    stock: true,
  },
  {
    id: 'candle-7',
    name: 'Luxury Spa Collection',
    category: 'Scented Candles',
    description: 'Premium spa blend with essential oils for wellness ambiance.',
    fragranceFamily: 'Aromatic Floral',
    topNotes: 'Eucalyptus, Mint',
    heartNotes: 'Lavender, Rose',
    baseNotes: 'Sandalwood, Musk',
    longevity: '50+ hours burn time',
    bestFor: 'Spa-like relaxation at home',
    occasion: 'Self-care, meditation, wellness',
    season: 'Year-round',
    size: '250g',
    price: '₦75,000',
    image: '/candle-luxury-spa.png',
    stock: true,
  },

  // REED DIFFUSERS
  {
    id: 'diffuser-1',
    name: 'Soft Jasmine',
    category: 'Reed Diffusers',
    description: 'Delicate jasmine fragrance for continuous home ambiance.',
    fragranceFamily: 'Floral',
    topNotes: 'Bergamot',
    heartNotes: 'Jasmine, Rose',
    baseNotes: 'Musk, Sandalwood',
    longevity: '30-40 days',
    bestFor: 'Bedroom, living room ambiance',
    occasion: 'Continuous home scenting',
    season: 'Year-round',
    size: '100ml',
    price: '₦28,000',
    image: '/diffuser-soft-jasmine.png',
    stock: true,
  },
  {
    id: 'diffuser-2',
    name: 'Warm Vanilla',
    category: 'Reed Diffusers',
    description: 'Comforting vanilla fragrance for welcoming home scent.',
    fragranceFamily: 'Vanilla Gourmand',
    topNotes: 'Caramel',
    heartNotes: 'Vanilla, Tonka',
    baseNotes: 'Musk, Amber',
    longevity: '35-45 days',
    bestFor: 'Living areas, entryways',
    occasion: 'Year-round home fragrance',
    season: 'Year-round',
    size: '100ml',
    price: '₦25,000',
    image: '/diffuser-warm-vanilla.png',
    stock: true,
  },
  {
    id: 'diffuser-3',
    name: 'Fresh Cotton',
    category: 'Reed Diffusers',
    description: 'Clean linen scent for fresh, airy home spaces.',
    fragranceFamily: 'Floral Musk',
    topNotes: 'Lemon',
    heartNotes: 'White Florals',
    baseNotes: 'Musk',
    longevity: '30-35 days',
    bestFor: 'Bathrooms, bedrooms',
    occasion: 'Daily home fragrance',
    season: 'Spring, Summer',
    size: '100ml',
    price: '₦24,000',
    image: '/reed-diffuser.png',
    stock: true,
  },
  {
    id: 'diffuser-4',
    name: 'White Tea',
    category: 'Reed Diffusers',
    description: 'Delicate white tea with mint for refreshing calm.',
    fragranceFamily: 'Herbal Aromatic',
    topNotes: 'Mint, Green Tea',
    heartNotes: 'White Tea',
    baseNotes: 'Musk, Lily',
    longevity: '32-38 days',
    bestFor: 'Home offices, study areas',
    occasion: 'Daily focus and ambiance',
    season: 'Spring, Summer',
    size: '100ml',
    price: '₦27,000',
    image: '/diffuser-white-tea.png',
    stock: true,
  },
  {
    id: 'diffuser-5',
    name: 'Royal Oud',
    category: 'Reed Diffusers',
    description: 'Premium oud fragrance for luxurious home spaces.',
    fragranceFamily: 'Oud',
    topNotes: 'Saffron',
    heartNotes: 'Oud',
    baseNotes: 'Amber, Musk',
    longevity: '40-50 days',
    bestFor: 'Living rooms, formal spaces',
    occasion: 'Special ambiance, entertaining',
    season: 'Autumn, Winter',
    size: '100ml',
    price: '₦60,000',
    image: '/diffuser-royal-oud.png',
    stock: true,
  },
  {
    id: 'diffuser-6',
    name: 'Lemongrass Serenity',
    category: 'Reed Diffusers',
    description: 'Uplifting lemongrass with zen-like calm for peaceful spaces.',
    fragranceFamily: 'Citrus Herbal',
    topNotes: 'Lemongrass, Ginger',
    heartNotes: 'Jasmine',
    baseNotes: 'Musk, Sandalwood',
    longevity: '35-40 days',
    bestFor: 'Home offices, meditation spaces',
    occasion: 'Daily inspiration and calm',
    season: 'Spring, Summer',
    size: '100ml',
    price: '₦32,000',
    image: '/diffuser-lemongrass.png',
    stock: true,
  },
  {
    id: 'diffuser-7',
    name: 'Luxury Home Collection',
    category: 'Reed Diffusers',
    description: 'Premium blend for sophisticated home ambiance.',
    fragranceFamily: 'Luxury Oriental',
    topNotes: 'Bergamot, Saffron',
    heartNotes: 'Rose, Oud',
    baseNotes: 'Sandalwood, Amber',
    longevity: '45-55 days',
    bestFor: 'Grand entrances, formal living areas',
    occasion: 'Year-round luxury ambiance',
    season: 'Year-round',
    size: '120ml',
    price: '₦85,000',
    image: '/reed-diffuser.png',
    stock: true,
  },

  // CAR FRAGRANCES
  {
    id: 'car-1',
    name: 'Executive Drive',
    category: 'Car Fragrances',
    description: 'Professional woody aromatic for the sophisticated commute.',
    fragranceFamily: 'Woody Aromatic',
    topNotes: 'Grapefruit',
    heartNotes: 'Cedarwood, Vetiver',
    baseNotes: 'Sandalwood, Musk',
    longevity: '30-40 days',
    bestFor: 'Professional settings, business cars',
    occasion: 'Daily commute, business travel',
    season: 'Year-round',
    size: 'Standard',
    price: '₦32,000',
    image: '/car-executive-drive.png',
    stock: true,
  },
  {
    id: 'car-2',
    name: 'Midnight Leather',
    category: 'Car Fragrances',
    description: 'Rich leather and spice fragrance for bold drivers.',
    fragranceFamily: 'Leather Aromatic',
    topNotes: 'Cardamom',
    heartNotes: 'Leather, Tobacco',
    baseNotes: 'Amber, Musk',
    longevity: '35-45 days',
    bestFor: 'Luxury vehicles, evening drives',
    occasion: 'Evening commutes, special trips',
    season: 'Autumn, Winter',
    size: 'Standard',
    price: '₦45,000',
    image: '/car-midnight-leather.png',
    stock: true,
  },
  {
    id: 'car-3',
    name: 'Fresh Escape',
    category: 'Car Fragrances',
    description: 'Crisp citrus for uplifting daily driving comfort.',
    fragranceFamily: 'Citrus Fresh',
    topNotes: 'Lemon, Grapefruit',
    heartNotes: 'Green Notes',
    baseNotes: 'Musk',
    longevity: '25-35 days',
    bestFor: 'Daily driving, summer commutes',
    occasion: 'Regular commuting',
    season: 'Spring, Summer',
    size: 'Standard',
    price: '₦20,000',
    image: '/car-fresh-escape.png',
    stock: true,
  },
  {
    id: 'car-4',
    name: 'Royal Oud Drive',
    category: 'Car Fragrances',
    description: 'Luxurious oud fragrance for elevated driving experience.',
    fragranceFamily: 'Oud',
    topNotes: 'Saffron',
    heartNotes: 'Oud',
    baseNotes: 'Amber, Musk',
    longevity: '40-50 days',
    bestFor: 'Premium vehicles, special occasions',
    occasion: 'Luxury driving, special trips',
    season: 'Year-round',
    size: 'Premium',
    price: '₦65,000',
    image: '/car-royal-oud-drive.png',
    stock: true,
  },
  {
    id: 'car-5',
    name: 'Ocean Breeze',
    category: 'Car Fragrances',
    description: 'Fresh aquatic fragrance for vacation vibes on the road.',
    fragranceFamily: 'Aquatic Citrus',
    topNotes: 'Sea Salt, Lemon',
    heartNotes: 'Aquatic Notes',
    baseNotes: 'Musk, Driftwood',
    longevity: '30-40 days',
    bestFor: 'Summer drives, casual trips',
    occasion: 'Holiday travel, weekend getaways',
    season: 'Spring, Summer',
    size: 'Standard',
    price: '₦28,000',
    image: '/car-ocean-breeze.png',
    stock: true,
  },
  {
    id: 'car-6',
    name: 'Golden Citrus',
    category: 'Car Fragrances',
    description: 'Energizing citrus and warm amber for every journey.',
    fragranceFamily: 'Citrus Amber',
    topNotes: 'Orange, Grapefruit',
    heartNotes: 'Neroli',
    baseNotes: 'Amber, Musk',
    longevity: '35-45 days',
    bestFor: 'Daily driving, business travel',
    occasion: 'Regular commuting',
    season: 'Year-round',
    size: 'Standard',
    price: '₦30,000',
    image: '/car-golden-citrus.png',
    stock: true,
  },
  {
    id: 'car-7',
    name: 'Luxury Auto Collection',
    category: 'Car Fragrances',
    description: 'Exclusive premium blend for the most discerning drivers.',
    fragranceFamily: 'Luxury Blend',
    topNotes: 'Bergamot, Saffron',
    heartNotes: 'Rose, Oud',
    baseNotes: 'Sandalwood, Amber',
    longevity: '50+ days',
    bestFor: 'Luxury vehicles, collectors',
    occasion: 'Exclusive driving experiences',
    season: 'Year-round',
    size: 'Premium',
    price: '₦100,000',
    image: '/car-luxury-auto.png',
    stock: true,
  },

  // GIFT COLLECTIONS
  {
    id: 'gift-1',
    name: 'Elegant Gift Box',
    category: 'Gift Collections',
    description: 'Beautifully packaged gift set with three premium fragrances for the discerning recipient.',
    fragranceFamily: 'Mixed Selection',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'Corporate gifts, appreciation',
    occasion: 'Holidays, anniversaries, appreciation',
    season: 'Year-round',
    size: '3 x 50ml',
    price: '₦120,000',
    image: '/gift-elegant-box.png',
    stock: true,
  },
  {
    id: 'gift-2',
    name: 'Couple\'s Luxury Collection',
    category: 'Gift Collections',
    description: 'Romantic gift set featuring complementary fragrances for couples in premium packaging.',
    fragranceFamily: 'Luxury Blend',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'Romantic gifts, couples',
    occasion: 'Anniversaries, weddings, engagements',
    season: 'Year-round',
    size: '2 x 75ml',
    price: '₦160,000',
    image: '/gift-collection.png',
    stock: true,
  },
  {
    id: 'gift-3',
    name: 'Executive Gift Hamper',
    category: 'Gift Collections',
    description: 'Professional gift collection including fragrance, candle and diffuser for business gifting.',
    fragranceFamily: 'Mixed Selection',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'Corporate gifting, executives',
    occasion: 'Business milestones, client appreciation',
    season: 'Year-round',
    size: 'Complete set',
    price: '₦200,000',
    image: '/gift-executive-hamper.png',
    stock: true,
  },
  {
    id: 'gift-4',
    name: 'Wedding Collection',
    category: 'Gift Collections',
    description: 'Celebratory collection perfect for weddings with matching his and her fragrances.',
    fragranceFamily: 'Luxury Blend',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'Weddings, newlyweds',
    occasion: 'Wedding gifts, celebrations',
    season: 'Year-round',
    size: '2 x 100ml',
    price: '₦280,000',
    image: '/gift-wedding-collection.png',
    stock: true,
  },
  {
    id: 'gift-5',
    name: 'VIP Prestige Collection',
    category: 'Gift Collections',
    description: 'Ultimate luxury collection featuring premium fragrances, oils and home scents.',
    fragranceFamily: 'Luxury Selection',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'VIPs, special occasions',
    occasion: 'Premium gifting, milestones',
    season: 'Year-round',
    size: 'Complete set',
    price: '₦400,000',
    image: '/gift-vip-prestige.png',
    stock: true,
  },
  {
    id: 'gift-6',
    name: 'Luxury Celebration Collection',
    category: 'Gift Collections',
    description: 'Festive collection celebrating special moments with an assortment of premium products.',
    fragranceFamily: 'Mixed Selection',
    topNotes: 'Varied',
    heartNotes: 'Varied',
    baseNotes: 'Varied',
    longevity: 'Varied',
    bestFor: 'Celebrations, special events',
    occasion: 'Promotions, celebrations, achievements',
    season: 'Year-round',
    size: 'Complete set',
    price: '₦320,000',
    image: '/gift-luxury-celebration.png',
    stock: true,
  },
  {
  id: 'gift-7',
  name: 'VIZZANG Royal Signature Box',
  category: 'Gift Collections',
  description: 'Exclusive limited edition gift set with signature VIZZANG fragrances in handcrafted packaging.',
  fragranceFamily: 'VIZZANG Signature',
    topNotes: 'Exclusive blend',
    heartNotes: 'Exclusive blend',
    baseNotes: 'Exclusive blend',
    longevity: '14+ hours',
    bestFor: 'Collectors, exclusive gifting',
    occasion: 'Major celebrations, VIP gifts',
    season: 'Year-round',
    size: '3 x 50ml + Accessories',
    price: '₦500,000',
    image: '/gift-royal-signature.png',
    stock: false,
  },
]

export function getProductsByCategory(category: string): Product[] {
  if (category === 'All') {
    return allProducts
  }
  return allProducts.filter(product => product.category === category)
}
